### ISSUE TITLE
Map is not loading on IE11

### ISSUE THREAD

**Issue by jakebellacera** [wattapp/superchargers#15]
<img width="446" alt="screen shot 2016-11-12 at 10 49 37 am" src="https://cloud.githubusercontent.com/assets/391085/20240135/bb6e2050-a8c5-11e6-86ad-0474929e8af7.png">

**Comment by jakebellacera** [comment]
I'm closing this issue for two reasons:
1. This is a mapbox issue.
2. It turns out that `Uint8ClampedArray` was not available in IE until [this Windows security patch](https://support.microsoft.com/en-us/kb/2929437#kb-link-25). While the Windows 8.1 Browserstack instance I was testing with does not have this patch, most Windows users should be OK.

**Comment by dewski** [comment]
What about displaying a IE11 alert to upgrade or view in another browser?
